apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-conversao
spec:
  selector:
    matchLabels:
      app: api-conversao
  template:
    metadata:
      labels:
        app: api-conversao
    spec:
      containers:
        - name: movies
          image: carlosvnc/api-conversao:v1
          ports:
          - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: conversao-service
spec:
  selector:
    app: conversao
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000
  type: NodePort

